apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-1
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    envFrom:
    - configMapRef:
          name: app-cm
    - secretRef:
          name: app-secret
    command: ['sh','-c', 'echo The application is running && sleep 3600']