apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    env:
    - name: FIRSTNAME
      valueFrom:
          configMapKeyRef:
            name: app-cm
            key: firstname 
    - name: LASTNAME
      valueFrom:
          configMapKeyRef:
            name: app-cm
            key: lastname
    - name: USERNAME
      valueFrom:
          secretKeyRef:
            name: app-secret
            key: username
    - name: PASSWORD
      valueFrom:
          secretKeyRef:
            name: app-secret
            key: password
    command: ['sh','-c', 'echo The application is running && sleep 3600']
   
