# This Creates a redis pod with no volume defined and volume is mounted into the pod at /data/redis path inside the container
# This has no backend storage which is empty and this data does not persist beyond lifecylce of the pod.
apiVersion: v1
kind: Pod 
metadata:
  name: redis 
spec:
  containers:
  - image: redis 
    name: redis
    volumeMounts:
    - name: redis-storage 
      mountPath: /data/redis 
  volumes:
    - name: redis-storage 
      emptyDir: {}
