apiVersion: v1
kind: Pod
metadata:
  name: goproxy
  labels:
    app: goproxy
spec:
  containers:
  - name: goproxy
    image: registry.k8s.io/goproxy:0.1
    ports:
    - containerPort: 8080
    readinessProbe: # Readiness probe will again perform readiness health check by openeing port 8080 agaisnt the container
      tcpSocket:
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
    livenessProbe: # Liveness probe will perform health check by opening a port 8080 against the container 
      tcpSocket:
        port: 3000
      initialDelaySeconds: 10 # wait for 10 sec before doing initial health check
      periodSeconds: 5 # perform health check every 5 sec 
      #Failure Threshold: This is the number of consecutive failed liveness probe attempts before Kubernetes considers the pod unhealthy and restarts it.
