apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    app: v1 
spec:
  type: NodePort
  selector:
      app: v1
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007