apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dev
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
      tier: frontend
  template:
    metadata:
      labels:
        env: dev
        tier: frontend
    spec:
      containers:
      - name: nginx-dev
        image: nginx
        ports:
        - containerPort: 80
