apiVersion: v1
kind: Pod
metadata:
  labels:
    env: dev
    tier: frontend
    type: app1
  name: nginx-sample
spec:
  containers:
  - name: nginx-sample
    image: nginx 
    ports:
    - containerPort: 80
