apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  nodeName: kind-control-plane 
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: config-volume
      mountPath: /var/app/config
  volumes:
  - name: config-volume
    persistentVolumeClaim:
      claimName: pvc-demo  # Name of the PersistentVolumeClaim
