# This creates a PV of local storage type with capacity of 512Mi and accessmode and the data is 
# stored in the host file system path at /data/config
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo
  labels:
    type: local 
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/config"